--
-- PostgreSQL database dump
--

-- Dumped from database version 12.0
-- Dumped by pg_dump version 12.0

-- Started on 2019-12-08 21:25:56 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3413 (class 1262 OID 16393)
-- Name: online-shop; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "online-shop" WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C' LC_CTYPE = 'C';


ALTER DATABASE "online-shop" OWNER TO postgres;

\connect -reuse-previous=on "dbname='online-shop'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 206 (class 1259 OID 16880)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16878)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16862)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 208 (class 1259 OID 16895)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16893)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16908)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16921)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16939)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 16870)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "Discriminator" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16394)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16962)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    "ID" integer NOT NULL,
    "Name" character varying(200) NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16960)
-- Name: categories_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."categories_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17120)
-- Name: discounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.discounts (
    "ID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "Percentage" numeric NOT NULL,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL
);


ALTER TABLE public.discounts OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17118)
-- Name: discounts_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.discounts ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."discounts_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 17175)
-- Name: invoice_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoice_details (
    "ID" bigint NOT NULL,
    "InvoiceID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "ItemQuantity" integer NOT NULL,
    "ItemPrice" numeric NOT NULL
);


ALTER TABLE public.invoice_details OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17173)
-- Name: invoice_details_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoice_details ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."invoice_details_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17100)
-- Name: invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invoices (
    "ID" bigint NOT NULL,
    "ApplicationUserID" bigint NOT NULL,
    "OrderID" bigint NOT NULL,
    "TotalValue" numeric NOT NULL,
    "DateIssued" timestamp without time zone NOT NULL,
    "ApplicationUserId" text
);


ALTER TABLE public.invoices OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17098)
-- Name: invoices_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invoices ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."invoices_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17135)
-- Name: order_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_details (
    "ID" bigint NOT NULL,
    "OrderID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "Quantity" integer NOT NULL
);


ALTER TABLE public.order_details OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17133)
-- Name: order_details_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_details ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."order_details_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17055)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    "ID" bigint NOT NULL,
    "ApplicationUserID" text,
    "ShippingMethodID" integer NOT NULL,
    "DateAndTime" timestamp without time zone NOT NULL,
    "Note" character varying(400),
    "ShippingMethodPrice" numeric NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17053)
-- Name: orders_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."orders_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17020)
-- Name: payment_methods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_methods (
    "ID" bigint NOT NULL,
    "PaymentTypeID" integer NOT NULL,
    "ApplicationUserID" bigint NOT NULL,
    "Value" character varying(512) NOT NULL,
    "ApplicationUserId" text
);


ALTER TABLE public.payment_methods OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17018)
-- Name: payment_methods_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_methods ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."payment_methods_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16969)
-- Name: payment_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_types (
    "ID" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public.payment_types OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16967)
-- Name: payment_types_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_types ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."payment_types_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 17040)
-- Name: producer_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producer_details (
    "ID" bigint NOT NULL,
    "ProducerID" integer NOT NULL,
    "PhoneNumber" character varying(30),
    "Email" character varying(200),
    "Address1" character varying(200),
    "Address2" character varying(200),
    "City" character varying(200),
    "Country" character varying(200)
);


ALTER TABLE public.producer_details OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17038)
-- Name: producer_details_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producer_details ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."producer_details_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16976)
-- Name: producers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producers (
    "ID" integer NOT NULL,
    "Name" character varying(200) NOT NULL
);


ALTER TABLE public.producers OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16974)
-- Name: producers_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producers ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."producers_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 17075)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    "ID" bigint NOT NULL,
    "ProducerID" integer NOT NULL,
    "CategoryID" integer NOT NULL,
    "SubcategoryID" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Price" numeric NOT NULL,
    "AvailableQuantity" integer NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17073)
-- Name: products_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."products_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 17155)
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    "ID" bigint NOT NULL,
    "ApplicationUserID" bigint NOT NULL,
    "ProductID" bigint NOT NULL,
    "Rating" integer NOT NULL,
    "Content" character varying(1024) NOT NULL,
    "ApplicationUserId" text
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17153)
-- Name: reviews_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."reviews_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16983)
-- Name: shipping_methods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipping_methods (
    "ID" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Price" numeric NOT NULL
);


ALTER TABLE public.shipping_methods OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16981)
-- Name: shipping_methods_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shipping_methods ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."shipping_methods_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 17008)
-- Name: subcategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subcategories (
    "ID" integer NOT NULL,
    "CategoryID" integer NOT NULL,
    "Name" character varying(200) NOT NULL
);


ALTER TABLE public.subcategories OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17006)
-- Name: subcategories_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subcategories ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."subcategories_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16993)
-- Name: user_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_details (
    "ID" bigint NOT NULL,
    "ApplicationUserID" text,
    "Name" character varying(128) NOT NULL,
    "Surname" character varying(200) NOT NULL,
    "Address1" character varying(200),
    "Address2" character varying(200),
    "Address3" character varying(200),
    "ZipCode" character varying(32),
    "City" character varying(200),
    "Country" character varying(200),
    "StateRegion" character varying(200)
);


ALTER TABLE public.user_details OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16991)
-- Name: user_details_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_details ALTER COLUMN "ID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."user_details_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3372 (class 0 OID 16880)
-- Dependencies: 206
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3369 (class 0 OID 16862)
-- Dependencies: 203
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- TOC entry 3374 (class 0 OID 16895)
-- Dependencies: 208
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- TOC entry 3375 (class 0 OID 16908)
-- Dependencies: 209
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- TOC entry 3376 (class 0 OID 16921)
-- Dependencies: 210
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- TOC entry 3377 (class 0 OID 16939)
-- Dependencies: 211
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- TOC entry 3370 (class 0 OID 16870)
-- Dependencies: 204
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount", "Discriminator") FROM stdin;
\.


--
-- TOC entry 3368 (class 0 OID 16394)
-- Dependencies: 202
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20191129200901_Initial	3.0.1
20191208193744_EntityClasses	3.0.1
20191208200220_EntityUpdate	3.0.1
20191208200553_EntityUpdatev2	3.0.1
20191208200826_EntityUpdatev3	3.0.1
20191208201415_EntityUpdatev4	3.0.1
20191208201508_EntityUpdatev5	3.0.1
20191208202156_EntityUpdate	3.0.1
\.


--
-- TOC entry 3379 (class 0 OID 16962)
-- Dependencies: 213
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories ("ID", "Name") FROM stdin;
\.


--
-- TOC entry 3401 (class 0 OID 17120)
-- Dependencies: 235
-- Data for Name: discounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.discounts ("ID", "ProductID", "Percentage", "StartTime", "EndTime") FROM stdin;
\.


--
-- TOC entry 3407 (class 0 OID 17175)
-- Dependencies: 241
-- Data for Name: invoice_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoice_details ("ID", "InvoiceID", "ProductID", "ItemQuantity", "ItemPrice") FROM stdin;
\.


--
-- TOC entry 3399 (class 0 OID 17100)
-- Dependencies: 233
-- Data for Name: invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.invoices ("ID", "ApplicationUserID", "OrderID", "TotalValue", "DateIssued", "ApplicationUserId") FROM stdin;
\.


--
-- TOC entry 3403 (class 0 OID 17135)
-- Dependencies: 237
-- Data for Name: order_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_details ("ID", "OrderID", "ProductID", "UnitPrice", "Quantity") FROM stdin;
\.


--
-- TOC entry 3395 (class 0 OID 17055)
-- Dependencies: 229
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders ("ID", "ApplicationUserID", "ShippingMethodID", "DateAndTime", "Note", "ShippingMethodPrice") FROM stdin;
\.


--
-- TOC entry 3391 (class 0 OID 17020)
-- Dependencies: 225
-- Data for Name: payment_methods; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_methods ("ID", "PaymentTypeID", "ApplicationUserID", "Value", "ApplicationUserId") FROM stdin;
\.


--
-- TOC entry 3381 (class 0 OID 16969)
-- Dependencies: 215
-- Data for Name: payment_types; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_types ("ID", "Name") FROM stdin;
\.


--
-- TOC entry 3393 (class 0 OID 17040)
-- Dependencies: 227
-- Data for Name: producer_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producer_details ("ID", "ProducerID", "PhoneNumber", "Email", "Address1", "Address2", "City", "Country") FROM stdin;
\.


--
-- TOC entry 3383 (class 0 OID 16976)
-- Dependencies: 217
-- Data for Name: producers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producers ("ID", "Name") FROM stdin;
\.


--
-- TOC entry 3397 (class 0 OID 17075)
-- Dependencies: 231
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products ("ID", "ProducerID", "CategoryID", "SubcategoryID", "Name", "Price", "AvailableQuantity") FROM stdin;
\.


--
-- TOC entry 3405 (class 0 OID 17155)
-- Dependencies: 239
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews ("ID", "ApplicationUserID", "ProductID", "Rating", "Content", "ApplicationUserId") FROM stdin;
\.


--
-- TOC entry 3385 (class 0 OID 16983)
-- Dependencies: 219
-- Data for Name: shipping_methods; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shipping_methods ("ID", "Name", "Price") FROM stdin;
\.


--
-- TOC entry 3389 (class 0 OID 17008)
-- Dependencies: 223
-- Data for Name: subcategories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subcategories ("ID", "CategoryID", "Name") FROM stdin;
\.


--
-- TOC entry 3387 (class 0 OID 16993)
-- Dependencies: 221
-- Data for Name: user_details; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_details ("ID", "ApplicationUserID", "Name", "Surname", "Address1", "Address2", "Address3", "ZipCode", "City", "Country", "StateRegion") FROM stdin;
\.


--
-- TOC entry 3414 (class 0 OID 0)
-- Dependencies: 205
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3415 (class 0 OID 0)
-- Dependencies: 207
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3416 (class 0 OID 0)
-- Dependencies: 212
-- Name: categories_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."categories_ID_seq"', 1, false);


--
-- TOC entry 3417 (class 0 OID 0)
-- Dependencies: 234
-- Name: discounts_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."discounts_ID_seq"', 1, false);


--
-- TOC entry 3418 (class 0 OID 0)
-- Dependencies: 240
-- Name: invoice_details_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."invoice_details_ID_seq"', 1, false);


--
-- TOC entry 3419 (class 0 OID 0)
-- Dependencies: 232
-- Name: invoices_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."invoices_ID_seq"', 1, false);


--
-- TOC entry 3420 (class 0 OID 0)
-- Dependencies: 236
-- Name: order_details_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."order_details_ID_seq"', 1, false);


--
-- TOC entry 3421 (class 0 OID 0)
-- Dependencies: 228
-- Name: orders_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."orders_ID_seq"', 1, false);


--
-- TOC entry 3422 (class 0 OID 0)
-- Dependencies: 224
-- Name: payment_methods_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."payment_methods_ID_seq"', 1, false);


--
-- TOC entry 3423 (class 0 OID 0)
-- Dependencies: 214
-- Name: payment_types_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."payment_types_ID_seq"', 1, false);


--
-- TOC entry 3424 (class 0 OID 0)
-- Dependencies: 226
-- Name: producer_details_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."producer_details_ID_seq"', 1, false);


--
-- TOC entry 3425 (class 0 OID 0)
-- Dependencies: 216
-- Name: producers_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."producers_ID_seq"', 1, false);


--
-- TOC entry 3426 (class 0 OID 0)
-- Dependencies: 230
-- Name: products_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."products_ID_seq"', 1, false);


--
-- TOC entry 3427 (class 0 OID 0)
-- Dependencies: 238
-- Name: reviews_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."reviews_ID_seq"', 1, false);


--
-- TOC entry 3428 (class 0 OID 0)
-- Dependencies: 218
-- Name: shipping_methods_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."shipping_methods_ID_seq"', 1, false);


--
-- TOC entry 3429 (class 0 OID 0)
-- Dependencies: 222
-- Name: subcategories_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."subcategories_ID_seq"', 1, false);


--
-- TOC entry 3430 (class 0 OID 0)
-- Dependencies: 220
-- Name: user_details_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."user_details_ID_seq"', 1, false);


--
-- TOC entry 3156 (class 2606 OID 16887)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3148 (class 2606 OID 16869)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3159 (class 2606 OID 16902)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3162 (class 2606 OID 16915)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3165 (class 2606 OID 16928)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3167 (class 2606 OID 16946)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3152 (class 2606 OID 16877)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3146 (class 2606 OID 16398)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3169 (class 2606 OID 16966)
-- Name: categories PK_categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT "PK_categories" PRIMARY KEY ("ID");


--
-- TOC entry 3204 (class 2606 OID 17127)
-- Name: discounts PK_discounts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT "PK_discounts" PRIMARY KEY ("ID");


--
-- TOC entry 3216 (class 2606 OID 17182)
-- Name: invoice_details PK_invoice_details; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_details
    ADD CONSTRAINT "PK_invoice_details" PRIMARY KEY ("ID");


--
-- TOC entry 3201 (class 2606 OID 17107)
-- Name: invoices PK_invoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT "PK_invoices" PRIMARY KEY ("ID");


--
-- TOC entry 3208 (class 2606 OID 17142)
-- Name: order_details PK_order_details; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "PK_order_details" PRIMARY KEY ("ID");


--
-- TOC entry 3192 (class 2606 OID 17062)
-- Name: orders PK_orders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "PK_orders" PRIMARY KEY ("ID");


--
-- TOC entry 3185 (class 2606 OID 17027)
-- Name: payment_methods PK_payment_methods; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT "PK_payment_methods" PRIMARY KEY ("ID");


--
-- TOC entry 3171 (class 2606 OID 16973)
-- Name: payment_types PK_payment_types; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_types
    ADD CONSTRAINT "PK_payment_types" PRIMARY KEY ("ID");


--
-- TOC entry 3188 (class 2606 OID 17047)
-- Name: producer_details PK_producer_details; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producer_details
    ADD CONSTRAINT "PK_producer_details" PRIMARY KEY ("ID");


--
-- TOC entry 3173 (class 2606 OID 16980)
-- Name: producers PK_producers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producers
    ADD CONSTRAINT "PK_producers" PRIMARY KEY ("ID");


--
-- TOC entry 3197 (class 2606 OID 17082)
-- Name: products PK_products; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "PK_products" PRIMARY KEY ("ID");


--
-- TOC entry 3212 (class 2606 OID 17162)
-- Name: reviews PK_reviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT "PK_reviews" PRIMARY KEY ("ID");


--
-- TOC entry 3175 (class 2606 OID 16990)
-- Name: shipping_methods PK_shipping_methods; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipping_methods
    ADD CONSTRAINT "PK_shipping_methods" PRIMARY KEY ("ID");


--
-- TOC entry 3181 (class 2606 OID 17012)
-- Name: subcategories PK_subcategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcategories
    ADD CONSTRAINT "PK_subcategories" PRIMARY KEY ("ID");


--
-- TOC entry 3178 (class 2606 OID 17000)
-- Name: user_details PK_user_details; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_details
    ADD CONSTRAINT "PK_user_details" PRIMARY KEY ("ID");


--
-- TOC entry 3150 (class 1259 OID 16957)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3154 (class 1259 OID 16952)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3157 (class 1259 OID 16954)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3160 (class 1259 OID 16955)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3163 (class 1259 OID 16956)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3202 (class 1259 OID 17193)
-- Name: IX_discounts_ProductID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_discounts_ProductID" ON public.discounts USING btree ("ProductID");


--
-- TOC entry 3213 (class 1259 OID 17194)
-- Name: IX_invoice_details_InvoiceID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_invoice_details_InvoiceID" ON public.invoice_details USING btree ("InvoiceID");


--
-- TOC entry 3214 (class 1259 OID 17195)
-- Name: IX_invoice_details_ProductID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_invoice_details_ProductID" ON public.invoice_details USING btree ("ProductID");


--
-- TOC entry 3198 (class 1259 OID 17196)
-- Name: IX_invoices_ApplicationUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_invoices_ApplicationUserId" ON public.invoices USING btree ("ApplicationUserId");


--
-- TOC entry 3199 (class 1259 OID 17197)
-- Name: IX_invoices_OrderID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_invoices_OrderID" ON public.invoices USING btree ("OrderID");


--
-- TOC entry 3205 (class 1259 OID 17198)
-- Name: IX_order_details_OrderID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_order_details_OrderID" ON public.order_details USING btree ("OrderID");


--
-- TOC entry 3206 (class 1259 OID 17199)
-- Name: IX_order_details_ProductID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_order_details_ProductID" ON public.order_details USING btree ("ProductID");


--
-- TOC entry 3189 (class 1259 OID 17200)
-- Name: IX_orders_ApplicationUserID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_orders_ApplicationUserID" ON public.orders USING btree ("ApplicationUserID");


--
-- TOC entry 3190 (class 1259 OID 17201)
-- Name: IX_orders_ShippingMethodID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_orders_ShippingMethodID" ON public.orders USING btree ("ShippingMethodID");


--
-- TOC entry 3182 (class 1259 OID 17202)
-- Name: IX_payment_methods_ApplicationUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_payment_methods_ApplicationUserId" ON public.payment_methods USING btree ("ApplicationUserId");


--
-- TOC entry 3183 (class 1259 OID 17203)
-- Name: IX_payment_methods_PaymentTypeID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_payment_methods_PaymentTypeID" ON public.payment_methods USING btree ("PaymentTypeID");


--
-- TOC entry 3186 (class 1259 OID 17204)
-- Name: IX_producer_details_ProducerID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_producer_details_ProducerID" ON public.producer_details USING btree ("ProducerID");


--
-- TOC entry 3193 (class 1259 OID 17205)
-- Name: IX_products_CategoryID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_products_CategoryID" ON public.products USING btree ("CategoryID");


--
-- TOC entry 3194 (class 1259 OID 17206)
-- Name: IX_products_ProducerID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_products_ProducerID" ON public.products USING btree ("ProducerID");


--
-- TOC entry 3195 (class 1259 OID 17207)
-- Name: IX_products_SubcategoryID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_products_SubcategoryID" ON public.products USING btree ("SubcategoryID");


--
-- TOC entry 3209 (class 1259 OID 17208)
-- Name: IX_reviews_ApplicationUserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_reviews_ApplicationUserId" ON public.reviews USING btree ("ApplicationUserId");


--
-- TOC entry 3210 (class 1259 OID 17209)
-- Name: IX_reviews_ProductID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_reviews_ProductID" ON public.reviews USING btree ("ProductID");


--
-- TOC entry 3179 (class 1259 OID 17210)
-- Name: IX_subcategories_CategoryID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_subcategories_CategoryID" ON public.subcategories USING btree ("CategoryID");


--
-- TOC entry 3176 (class 1259 OID 17211)
-- Name: IX_user_details_ApplicationUserID; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_user_details_ApplicationUserID" ON public.user_details USING btree ("ApplicationUserID");


--
-- TOC entry 3149 (class 1259 OID 16953)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3153 (class 1259 OID 16958)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3217 (class 2606 OID 16888)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3218 (class 2606 OID 16903)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3219 (class 2606 OID 16916)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3220 (class 2606 OID 16929)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3221 (class 2606 OID 16934)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3222 (class 2606 OID 16947)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3235 (class 2606 OID 17128)
-- Name: discounts FK_discounts_products_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.discounts
    ADD CONSTRAINT "FK_discounts_products_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.products("ID") ON DELETE CASCADE;


--
-- TOC entry 3240 (class 2606 OID 17183)
-- Name: invoice_details FK_invoice_details_invoices_InvoiceID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_details
    ADD CONSTRAINT "FK_invoice_details_invoices_InvoiceID" FOREIGN KEY ("InvoiceID") REFERENCES public.invoices("ID") ON DELETE CASCADE;


--
-- TOC entry 3241 (class 2606 OID 17188)
-- Name: invoice_details FK_invoice_details_products_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoice_details
    ADD CONSTRAINT "FK_invoice_details_products_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.products("ID") ON DELETE CASCADE;


--
-- TOC entry 3233 (class 2606 OID 17108)
-- Name: invoices FK_invoices_AspNetUsers_ApplicationUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT "FK_invoices_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3234 (class 2606 OID 17113)
-- Name: invoices FK_invoices_orders_OrderID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT "FK_invoices_orders_OrderID" FOREIGN KEY ("OrderID") REFERENCES public.orders("ID") ON DELETE CASCADE;


--
-- TOC entry 3236 (class 2606 OID 17143)
-- Name: order_details FK_order_details_orders_OrderID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "FK_order_details_orders_OrderID" FOREIGN KEY ("OrderID") REFERENCES public.orders("ID") ON DELETE CASCADE;


--
-- TOC entry 3237 (class 2606 OID 17148)
-- Name: order_details FK_order_details_products_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT "FK_order_details_products_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.products("ID") ON DELETE CASCADE;


--
-- TOC entry 3228 (class 2606 OID 17063)
-- Name: orders FK_orders_AspNetUsers_ApplicationUserID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "FK_orders_AspNetUsers_ApplicationUserID" FOREIGN KEY ("ApplicationUserID") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3229 (class 2606 OID 17068)
-- Name: orders FK_orders_shipping_methods_ShippingMethodID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT "FK_orders_shipping_methods_ShippingMethodID" FOREIGN KEY ("ShippingMethodID") REFERENCES public.shipping_methods("ID") ON DELETE CASCADE;


--
-- TOC entry 3225 (class 2606 OID 17028)
-- Name: payment_methods FK_payment_methods_AspNetUsers_ApplicationUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT "FK_payment_methods_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3226 (class 2606 OID 17033)
-- Name: payment_methods FK_payment_methods_payment_types_PaymentTypeID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT "FK_payment_methods_payment_types_PaymentTypeID" FOREIGN KEY ("PaymentTypeID") REFERENCES public.payment_types("ID") ON DELETE CASCADE;


--
-- TOC entry 3227 (class 2606 OID 17048)
-- Name: producer_details FK_producer_details_producers_ProducerID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producer_details
    ADD CONSTRAINT "FK_producer_details_producers_ProducerID" FOREIGN KEY ("ProducerID") REFERENCES public.producers("ID") ON DELETE CASCADE;


--
-- TOC entry 3230 (class 2606 OID 17083)
-- Name: products FK_products_categories_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FK_products_categories_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public.categories("ID") ON DELETE CASCADE;


--
-- TOC entry 3231 (class 2606 OID 17088)
-- Name: products FK_products_producers_ProducerID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FK_products_producers_ProducerID" FOREIGN KEY ("ProducerID") REFERENCES public.producers("ID") ON DELETE CASCADE;


--
-- TOC entry 3232 (class 2606 OID 17093)
-- Name: products FK_products_subcategories_SubcategoryID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "FK_products_subcategories_SubcategoryID" FOREIGN KEY ("SubcategoryID") REFERENCES public.subcategories("ID") ON DELETE CASCADE;


--
-- TOC entry 3238 (class 2606 OID 17163)
-- Name: reviews FK_reviews_AspNetUsers_ApplicationUserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT "FK_reviews_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3239 (class 2606 OID 17168)
-- Name: reviews FK_reviews_products_ProductID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT "FK_reviews_products_ProductID" FOREIGN KEY ("ProductID") REFERENCES public.products("ID") ON DELETE CASCADE;


--
-- TOC entry 3224 (class 2606 OID 17013)
-- Name: subcategories FK_subcategories_categories_CategoryID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subcategories
    ADD CONSTRAINT "FK_subcategories_categories_CategoryID" FOREIGN KEY ("CategoryID") REFERENCES public.categories("ID") ON DELETE CASCADE;


--
-- TOC entry 3223 (class 2606 OID 17001)
-- Name: user_details FK_user_details_AspNetUsers_ApplicationUserID; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_details
    ADD CONSTRAINT "FK_user_details_AspNetUsers_ApplicationUserID" FOREIGN KEY ("ApplicationUserID") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


-- Completed on 2019-12-08 21:25:57 CET

--
-- PostgreSQL database dump complete
--

